### ISSUE TITLE
Joypad auto-read disable not present in PDF circuit

### ISSUE THREAD

**Issue by Fiskbit** [rgalland/SNES_S-CPU_Schematics#3]
Based on some recent tests by undisbeliever, it seems that clearing AUTO_JP_EN during auto-read immediately stops the auto-read process and clears AUTO_JP_READING on all tested CPU revisions. This isn't possible with the auto-read circuit on the "SNES JP REGISTERS" sheet of the S-CPU schematic PDF, which only has AUTO_JP_EN as an input latched on JP_CLK that controls a /RESET signal responsible for starting, not stopping, auto-read. The test result suggests that the VAWR DFFR should actually have a /SET input hooked up to AUTO_JP_EN so that clearing it causes AUTO_JP_READING to immediately become 0, halting the auto-read clock.

Can you verify whether there is a mistake in the circuit here? If VAWR does not actually have a AUTO_JP_EN /SET input, is AUTO_JP_EN connected to some other place in the circuit that might explain this behavior?

**Comment by rgalland** [comment]
Nice one. I'll look into it.

Envoyé à partir de Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________
From: Fiskbit ***@***.***>
Sent: Saturday, December 21, 2024 7:50:43 AM
To: rgalland/SNES_S-CPU_Schematics ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [rgalland/SNES_S-CPU_Schematics] Joypad auto-read disable not present in PDF circuit (Issue #3)


Based on some recent tests by undisbeliever, it seems that clearing AUTO_JP_EN during auto-read immediately stops the auto-read process and clears AUTO_JP_READING on all tested CPU revisions. This isn't possible with the auto-read circuit on the "SNES JP REGISTERS" sheet of the S-CPU schematic PDF, which only has AUTO_JP_EN as an input latched on JP_CLK that controls a /RESET signal responsible for starting, not stopping, auto-read. The test result suggests that the VAWR DFFR should actually have a /SET input hooked up to AUTO_JP_EN so that clearing it causes AUTO_JP_READING to immediately become 0, halting the auto-read clock.

Can you verify whether there is a mistake in the circuit here? If VAWR does not actually have a AUTO_JP_EN /SET input, is AUTO_JP_EN connected to some other place in the circuit that might explain this behavior?

**Comment by rgalland** [comment]
@Fiskbit , I'm making the edits right now but it is taking a bit longer than expecting since switching to a newer version of Kicad and trying to clear the warnings. It was a mistake on that flip flop you identified that is an SR type flip flop. Please expect the updated version to be ready soon.

**Comment by Fiskbit** [comment]
I'm glad to hear it's just this simple difference. Thank you very much for looking into this.

**Comment by rgalland** [comment]
@Fiskbit , changes and release done. Using a newer version of kicad has created thousands of warning because of grid size which I have started to go through but there are too of many of them. I'll keep these for the next issue as you are bound to find some more issue.
